-- Falta cabeçalho e limpar 'AS' e alinhar.
SELECT t1.cte_id,
       t1.emp_id,
       t1.clie_remetente_id,
       t1.clie_coleta_id,
       t1.clie_expedidor_id,
       t1.clie_recebedor_id,
       t1.clie_destinatario_id,
       t1.clie_entrega_id,
       t1.clie_tomador_id,
       t1.cid_id_origem,
       t1.cid_id_destino,
       t1.cid_id_passagem,
       t1.prod_id,
       t1.cte_versao_leiaute_xml,
       t1.cte_minuta,
       t1.cte_modelo,
       t1.cte_serie,
       t1.cte_numero,
       t1.cte_chave,
       t1.cte_data_hora_emissao,
       t1.cte_remetente,
       t1.cte_outro_local_coleta,
       t1.cte_expedidor,
       t1.cte_recebedor,
       t1.cte_destinatario,
       t1.cte_outro_local_entrega,
       t1.cte_tomador,
       t1.cte_modal,
       t1.cte_emissora_master,
       t1.cte_cia_master,
       t1.cte_serie_master,
       t1.cte_numero_master,
       t1.cte_operacional_master,
       t1.cte_chave_master,
       t1.cte_chave_referenciado,
       t1.cte_data_emissao_declaracao_tom,
       t1.cte_natureza_operacao,
       t1.cte_tipo_servico,
       t1.cte_tipo_do_cte,
       t1.cte_forma_emissao,
       t1.cte_codigo_rota,
       t1.cte_forma_pgto,
       t1.cte_impressao_dacte,
       t1.cte_cfop,
       t1.cte_tabela_frete,
       t1.cte_tabela_id,
       t1.redespacho_id,
       t1.cte_frete_manual,
       t1.cte_carac_adic_transp,
       t1.cte_carac_adic_servico,
       t1.cte_emissor,
       t1.cte_retira,
       t1.cte_detalhe_retira,
       t1.cte_tp_data_entrega,
       t1.cte_data_programada,
       t1.cte_data_inicial,
       t1.cte_data_final,
       t1.cte_tp_hora_entrega,
       t1.cte_hora_programada,
       t1.cte_hora_inicial,
       t1.cte_hora_final,
       t1.cte_obs_gerais,
       t1.cte_outras_carac_carga,
       t1.cte_peso_bruto,
       t1.cte_peso_cubado,
       t1.cte_peso_bc,
       t1.cte_cubagem_m3,
       t1.cte_qtde_volumes,
       t1.cte_valor_carga,
       t1.cte_valor_total,
       t1.cte_codigo_sit_tributaria,
       t1.cte_perc_reduc_bc,
       t1.cte_valor_bc,
       t1.cte_aliquota_icms,
       t1.cte_valor_icms,
       t1.cte_valor_cred_outorgado,
       t1.cte_valor_pis,
       t1.cte_valor_cofins,
       t1.cte_info_fisco,
       t1.cte_tipo_doc_anexo,
       t1.cte_data_entrega_prevista,
       t1.cte_data_entrega_efetuada,
       t1.cte_indicador_lotacao,
       t1.cte_ciot,
       t1.cte_situacao,
       t1.cte_xml,
       t1.cte_pdf,
       t1.cte_cancelado_xml,
       t1.cte_cancelado_pdf,
       t1.cte_dacte_impresso,
       t1.cte_cadastrado_por,
       t1.cte_cadastrado_em,
       t1.cte_alterado_por,
       t1.cte_alterado_em,
       t1.cte_versao,
       nt1.cte_tipo_coleta,
       nt1.cte_faturado,
       t1.rem_razao_social,
       t1.rem_nome_fantasia,
       t1.rem_cnpj,
       t1.rem_cpf,
       t1.rem_cnpj_cpf,
       t1.rem_ie,
       t1.rem_rg,
       t1.rem_im,
       t1.rem_icms,
       t1.rem_end_logradouro,
       t1.rem_end_numero,
       t1.rem_end_complemento,
       t1.rem_end_bairro,
       t1.rem_end_cep,
       t1.rem_fone,
       t1.rem_cid_codigo_uf,
       t1.rem_cid_codigo_municipio,
       t1.rem_cid_municipio,
       t1.rem_cid_uf AS rem_cid_uf,
       t1.rem_cid_sigla AS rem_cid_sigla,
       t1.rem_cid_nome_aeroporto AS rem_cid_nome_aeroporto,
       t1.rem_cid_nome AS rem_cid_nome,
       t1.rem_cid_nome_completo AS rem_cid_nome_completo,
       t1.col_razao_social AS col_razao_social,
       t1.col_nome_fantasia AS col_nome_fantasia,
       t1.col_cnpj AS col_cnpj,
       t1.col_cpf AS col_cpf,
       t1.col_cnpj_cpf AS col_cnpj_cpf,
       t1.col_ie AS col_ie,
       t1.col_rg AS col_rg,
       t1.col_im AS col_im,
       t1.col_icms AS col_icms,
       t1.col_end_logradouro AS col_end_logradouro,
       t1.col_end_numero AS col_end_numero,
       t1.col_end_complemento AS col_end_complemento,
       t1.col_end_bairro AS col_end_bairro,
       t1.col_end_cep AS col_end_cep,
       t1.col_fone AS col_fone,
       t1.col_cid_codigo_uf AS col_cid_codigo_uf,
       t1.col_cid_codigo_municipio AS col_cid_codigo_municipio,
       t1.col_cid_municipio AS col_cid_municipio,
       t1.col_cid_uf AS col_cid_uf,
       t1.col_cid_sigla AS col_cid_sigla,
       t1.col_cid_nome_aeroporto AS col_cid_nome_aeroporto,
       t1.col_cid_nome AS col_cid_nome,
       t1.col_cid_nome_completo AS col_cid_nome_completo,
       t1.exp_razao_social AS exp_razao_social,
       t1.exp_nome_fantasia AS exp_nome_fantasia,
       t1.exp_cnpj AS exp_cnpj,
       t1.exp_cpf AS exp_cpf,
       t1.exp_cnpj_cpf AS exp_cnpj_cpf,
       t1.exp_ie AS exp_ie,
       t1.exp_rg AS exp_rg,
       t1.exp_im AS exp_im,
       t1.exp_icms AS exp_icms,
       t1.exp_end_logradouro AS exp_end_logradouro,
       t1.exp_end_numero AS exp_end_numero,
       t1.exp_end_complemento AS exp_end_complemento,
       t1.exp_end_bairro AS exp_end_bairro,
       t1.exp_end_cep AS exp_end_cep,
       t1.exp_fone AS exp_fone,
       t1.exp_cid_codigo_uf AS exp_cid_codigo_uf,
       t1.exp_cid_codigo_municipio AS exp_cid_codigo_municipio,
       t1.exp_cid_municipio AS exp_cid_municipio,
       t1.exp_cid_uf AS exp_cid_uf,
       t1.exp_cid_sigla AS exp_cid_sigla,
       t1.exp_cid_nome_aeroporto AS exp_cid_nome_aeroporto,
       t1.exp_cid_nome AS exp_cid_nome,
       t1.exp_cid_nome_completo AS exp_cid_nome_completo,
       t1.rec_razao_social AS rec_razao_social,
       t1.rec_nome_fantasia AS rec_nome_fantasia,
       t1.rec_cnpj AS rec_cnpj,
       t1.rec_cpf AS rec_cpf,
       t1.rec_cnpj_cpf AS rec_cnpj_cpf,
       t1.rec_ie AS rec_ie,
       t1.rec_rg AS rec_rg,
       t1.rec_im AS rec_im,
       t1.rec_icms AS rec_icms,
       t1.rec_end_logradouro AS rec_end_logradouro,
       t1.rec_end_numero AS rec_end_numero,
       t1.rec_end_complemento AS rec_end_complemento,
       t1.rec_end_bairro AS rec_end_bairro,
       t1.rec_end_cep AS rec_end_cep,
       t1.rec_fone AS rec_fone,
       t1.rec_cid_codigo_uf AS rec_cid_codigo_uf,t1.rec_cid_codigo_municipio AS rec_cid_codigo_municipio,t1.rec_cid_municipio AS rec_cid_municipio,t1.rec_cid_uf AS rec_cid_uf,t1.rec_cid_sigla AS rec_cid_sigla,t1.rec_cid_nome_aeroporto AS rec_cid_nome_aeroporto,t1.rec_cid_nome AS rec_cid_nome,t1.rec_cid_nome_completo AS rec_cid_nome_completo,t1.des_razao_social AS des_razao_social,t1.des_nome_fantasia AS des_nome_fantasia,t1.des_cnpj AS des_cnpj,t1.des_cpf AS des_cpf,t1.des_cnpj_cpf AS des_cnpj_cpf,t1.des_ie AS des_ie,t1.des_rg AS des_rg,t1.des_im AS des_im,t1.des_icms AS des_icms,t1.des_end_logradouro AS des_end_logradouro,t1.des_end_numero AS des_end_numero,t1.des_end_complemento AS des_end_complemento,t1.des_end_bairro AS des_end_bairro,t1.des_end_cep AS des_end_cep,t1.des_fone AS des_fone,t1.des_cid_codigo_uf AS des_cid_codigo_uf,t1.des_cid_codigo_municipio AS des_cid_codigo_municipio,t1.des_cid_municipio AS des_cid_municipio,t1.des_cid_uf AS des_cid_uf,t1.des_cid_sigla AS des_cid_sigla,t1.des_cid_nome_aeroporto AS des_cid_nome_aeroporto,t1.des_cid_nome AS des_cid_nome,t1.des_cid_nome_completo AS des_cid_nome_completo,t1.ent_razao_social AS ent_razao_social,t1.ent_nome_fantasia AS ent_nome_fantasia,t1.ent_cnpj AS ent_cnpj,t1.ent_cpf AS ent_cpf,t1.ent_cnpj_cpf AS ent_cnpj_cpf,t1.ent_ie AS ent_ie,t1.ent_rg AS ent_rg,t1.ent_im AS ent_im,t1.ent_icms AS ent_icms,t1.ent_end_logradouro AS ent_end_logradouro,t1.ent_end_numero AS ent_end_numero,t1.ent_end_complemento AS ent_end_complemento,t1.ent_end_bairro AS ent_end_bairro,t1.ent_end_cep AS ent_end_cep,t1.ent_fone AS ent_fone,t1.ent_cid_codigo_uf AS ent_cid_codigo_uf,t1.ent_cid_codigo_municipio AS ent_cid_codigo_municipio,t1.ent_cid_municipio AS ent_cid_municipio,t1.ent_cid_uf AS ent_cid_uf,t1.ent_cid_sigla AS ent_cid_sigla,t1.ent_cid_nome_aeroporto AS ent_cid_nome_aeroporto,t1.ent_cid_nome AS ent_cid_nome,t1.ent_cid_nome_completo AS ent_cid_nome_completo,t1.tom_razao_social AS tom_razao_social,t1.tom_nome_fantasia AS tom_nome_fantasia,t1.tom_cnpj AS tom_cnpj,t1.tom_cpf AS tom_cpf,t1.tom_cnpj_cpf AS tom_cnpj_cpf,t1.tom_ie AS tom_ie,t1.tom_rg AS tom_rg,t1.tom_im AS tom_im,t1.tom_icms AS tom_icms,t1.tom_end_logradouro AS tom_end_logradouro,t1.tom_end_numero AS tom_end_numero,t1.tom_end_complemento AS tom_end_complemento,t1.tom_end_bairro AS tom_end_bairro,t1.tom_end_cep AS tom_end_cep,t1.tom_fone AS tom_fone,t1.tom_cid_codigo_uf AS tom_cid_codigo_uf,t1.tom_cid_codigo_municipio AS tom_cid_codigo_municipio,t1.tom_cid_municipio AS tom_cid_municipio,t1.tom_cid_uf AS tom_cid_uf,t1.tom_cid_sigla AS tom_cid_sigla,t1.tom_cid_nome_aeroporto AS tom_cid_nome_aeroporto,t1.tom_cid_nome AS tom_cid_nome,t1.tom_cid_nome_completo AS tom_cid_nome_completo,t1.cid_origem_codigo_uf AS cid_origem_codigo_uf,t1.cid_origem_codigo_municipio AS cid_origem_codigo_municipio,t1.cid_origem_municipio AS cid_origem_municipio,t1.cid_origem_uf AS cid_origem_uf,t1.cid_origem_sigla AS cid_origem_sigla,t1.cid_origem_nome_aeroporto AS cid_origem_nome_aeroporto,t1.cid_origem_nome AS cid_origem_nome,t1.cid_origem_nome_completo AS cid_origem_nome_completo,t1.cid_destino_codigo_uf AS cid_destino_codigo_uf,t1.cid_destino_codigo_municipio AS cid_destino_codigo_municipio,t1.cid_destino_municipio AS cid_destino_municipio,t1.cid_destino_uf AS cid_destino_uf,t1.cid_destino_sigla AS cid_destino_sigla,t1.cid_destino_nome_aeroporto AS cid_destino_nome_aeroporto,t1.cid_destino_nome AS cid_destino_nome,t1.cid_destino_nome_completo AS cid_destino_nome_completo,t1.cid_passagem_codigo_uf AS cid_passagem_codigo_uf,t1.cid_passagem_codigo_municipio AS cid_passagem_codigo_municipio,t1.cid_passagem_municipio AS cid_passagem_municipio,t1.cid_passagem_uf AS cid_passagem_uf,t1.cid_passagem_sigla AS cid_passagem_sigla,t1.cid_passagem_nome_aeroporto AS cid_passagem_nome_aeroporto,t1.cid_passagem_nome AS cid_passagem_nome,t1.cid_passagem_nome_completo AS cid_passagem_nome_completo,t1.iic_codigo AS iic_codigo,t1.gt_id_codigo AS gt_id_codigo,t1.produto_predominante_nome AS produto_predominante_nome,t1.produto_predominante AS produto_predominante,t1.produto_predominante_iic AS produto_predominante_iic,t1.produto_predominante_gt AS produto_predominante_gt,t1.cte_modal_nome AS cte_modal_nome,t1.cte_tipo_servico_nome AS cte_tipo_servico_nome,t1.cte_tipo_do_cte_nome AS cte_tipo_do_cte_nome,t1.cte_forma_emissao_nome AS cte_forma_emissao_nome,t1.cte_remetente_nome AS cte_remetente_nome,t1.cte_destinatario_nome AS cte_destinatario_nome,t1.cte_tomador_nome AS cte_tomador_nome,t1.cte_forma_pgto_nome AS cte_forma_pgto_nome,t1.cte_impressao_dacte_nome AS cte_impressao_dacte_nome,t1.cte_tp_data_entrega_nome AS cte_tp_data_entrega_nome,t1.cte_tp_hora_entrega_nome AS cte_tp_hora_entrega_nome,t1.cte_codigo_sit_tributaria_nome AS cte_codigo_sit_tributaria_nome,t1.cte_tipo_doc_anexo_nome AS cte_tipo_doc_anexo_nome,t1.cte_data_hora_autorizacao AS cte_data_hora_autorizacao,t1.cte_cadastrado_por_nome AS cte_cadastrado_por_nome,t1.cte_alterado_por_nome AS cte_alterado_por_nome,t1.recebedor_nome AS recebedor_nome,t1.recebedor_doc AS recebedor_doc,t1.cte_data_entrega_ultima AS cte_data_entrega_ultima,t1.cte_perc_entregue AS cte_perc_entregue,t1.lista_documentos AS lista_documentos,t1.lista_documentos_numeros AS lista_documentos_numeros,t1.cte_exibe_consulta_cliente AS cte_exibe_consulta_cliente,t2.cte_doc_serie AS cte_doc_serie,t2.cte_doc_data_emissao AS cte_doc_data_emissao,t2.cte_doc_numero AS cte_doc_numero,t2.cte_doc_cfop AS cte_doc_cfop,t2.cte_doc_modelo AS cte_doc_modelo,t2.cte_doc_volumes AS cte_doc_volumes,t2.cte_doc_bc_icms AS cte_doc_bc_icms,t2.cte_doc_valor_icms AS cte_doc_valor_icms,t2.cte_doc_bc_icms_st AS cte_doc_bc_icms_st,t2.cte_doc_valor_icms_st AS cte_doc_valor_icms_st,t2.cte_doc_peso_total AS cte_doc_peso_total,t2.cte_doc_pin AS cte_doc_pin,t2.cte_doc_valor_produtos AS cte_doc_valor_produtos,t2.cte_doc_valor_nota AS cte_doc_valor_nota,t2.cte_doc_chave_nfe AS cte_doc_chave_nfe,t2.cte_doc_tipo_doc AS cte_doc_tipo_doc,t2.cte_doc_descricao AS cte_doc_descricao,t3.cte_ocor_id AS cte_ocor_id,cast(t3.cte_ocor_quando as date) AS cte_ocor_quando_data,cast(t3.cte_ocor_quando as time) AS cte_ocor_quando_hora,t3.cte_ocor_cia_aerea AS cte_ocor_cia_aerea,t3.cte_ocor_voo AS cte_ocor_voo,t3.cte_ocor_base AS cte_ocor_base,t3.cte_ocor_serie_master AS cte_ocor_serie_master,t3.cte_ocor_numero_master AS cte_ocor_numero_master,t3.cte_ocor_operacional_master AS cte_ocor_operacional_master,t3.cte_ocor_chave_master AS cte_ocor_chave_master,t3.cte_ocor_volumes AS cte_ocor_volumes,t3.cte_ocor_peso_bruto AS cte_ocor_peso_bruto,t3.cte_ocor_entregador_nome AS cte_ocor_entregador_nome,t3.cte_ocor_entregador_doc AS cte_ocor_entregador_doc,t3.cte_ocor_recebedor_nome AS cte_ocor_recebedor_nome,t3.cte_ocor_recebedor_doc AS cte_ocor_recebedor_doc,t3.cte_ocor_nota AS cte_ocor_nota,t4.ocor_codigo AS ocor_codigo,t4.ocor_descricao AS ocor_descricao,t4.ocor_modal AS ocor_modal,t4.ocor_caracteristica AS ocor_caracteristica,
       concat_ws(' - ',t4.ocor_codigo,t4.ocor_descricao) AS ocor_nome,
       concat_ws(' - ',t4.ocor_modal,t4.ocor_caracteristica) AS ocor_modal_caracteristica
FROM view_ctes t1 
join ctes_documentos t2 on t2.cte_id = t1.cte_id
left join ctes_ocorrencias t3 on t3.cte_doc_id = t2.cte_doc_id
left join ocorrencias t4 on t4.ocor_id = t3.ocor_id
