-- Atualizacao em 2021-11-22 as 19:45 - Adicionado coluna edi_caixa_postal, edi_conemb, edi_notfis, edi_ocoren, edi_doccob, edi_ftp_url, edi_ftp_server, edi_ftp_user_id e edi_ftp_password
-- Atualização em 2021-11-26 as 19:28 - Adicionado coluna edi_ftp_remote_path
CREATE OR REPLACE VIEW view_clientes AS
SELECT t1.clie_id,
       t1.clie_categoria,
       t1.clie_ativo,
       t1.clie_tipo_documento,
       t1.emp_id,
       t1.clie_razao_social,
       t1.clie_nome_fantasia,
       t1.clie_tipo_estabelecimento,
       t1.clie_cnpj,
       t1.clie_ie_isento,
       t1.clie_inscr_estadual,
       t1.clie_inscr_municipal,
       t1.clie_contrib_icms,
       t1.clie_cpf,
       t1.clie_rg,
       t1.clie_situacao_cadastral,
       t1.clie_logradouro,
       t1.clie_numero,
       t1.clie_complemento,
       t1.clie_bairro,
       t1.clie_cep,
       t1.cid_id,
       t1.clie_fone1,
       t1.clie_fone2,
       t1.clie_seguradora,
       t1.clie_apolice,
       t1.clie_forma_aplicar_seguro,
       t1.clie_seguro_desconto,
       t1.clie_seguro_intra_estadual,
       t1.clie_seguro_inter_estadual,
       t1.clie_seguro_adval_tipo_1,
       t1.clie_seguro_adval_tipo_2,
       t1.clie_tom_aceita_frete_pago,
       t1.clie_tom_aceita_frete_a_pagar,
       t1.clie_tom_aceita_frete_outros,
       t1.clie_tom_aceita_suframa,
       t1.clie_tom_tabela,
       t1.clie_tom_taxa_sefaz,
       t1.clie_des_aceita_frete_a_pagar,
       t1.clie_des_inscricao_suframa,
       t1.clie_codigo_transporte,
       t1.rota_id,
       t1.clie_sequencia_rota,
       t1.clie_codigo_antigo,
       t1.clie_gris_percentual,
       t1.clie_gris_valor_minimo,
       t1.clie_login,
       t1.clie_senha,
       t1.edi_caixa_postal,
       t1.edi_conemb,
       t1.edi_notfis,
       t1.edi_ocoren,
       t1.edi_doccob,
       t1.edi_ftp_url,
       t1.edi_ftp_server,
       t1.edi_ftp_user_id,
       t1.edi_ftp_password,
       t1.edi_ftp_remote_path,
       t1.clie_cadastrado_por,
       t1.clie_cadastrado_em,
       t1.clie_alterado_por,
       t1.clie_alterado_em,
       t1.clie_versao,
       t2.user_nome AS clie_cadastrado_por_nome,
       t3.user_nome AS clie_alterado_por_nome,
       IF((t1.emp_id > 0),0,1) AS clie_compartilhado,
       IF((t1.clie_categoria = 0),'0 - Remetente',IF((t1.clie_categoria = 1),'1 - Expedidor',IF((t1.clie_categoria = 2),'2 - Recebedor',IF((t1.clie_categoria = 3),'3 - Destinatário',IF((t1.clie_categoria = 4),'4 - Todos','5 - Representante'))))) AS clie_categoria_nome,
       t4.cid_codigo_municipio,
       t4.cid_municipio,
       t4.cid_uf,
       t4.cid_sigla,
       t4.cid_nome_aeroporto,
       IF(((t4.cid_sigla is not null) AND (t4.cid_sigla <> '') AND (t4.cid_nome_aeroporto is not null) AND (t4.cid_nome_aeroporto <> '')),concat(t4.cid_uf,' - ',t4.cid_municipio,' (',t4.cid_sigla,' ',t4.cid_nome_aeroporto,')'),concat(t4.cid_uf,' - ',t4.cid_municipio)) AS cid_nome,
       t5.rota_codigo,
       t5.rota_descricao,
       concat_ws(' - ',t5.rota_codigo,t5.rota_descricao) AS rota_nome,
       t6.clie_id_fk,
       t6.cliefat_status_cobranca,
       t6.cliefat_tipo_carteira,
       t6.cliefat_dias_ao_vecto,
       t6.cliefat_dias_protestar,
       t6.cliefat_dias_em_atraso,
       t6.auto_inadimplente,
       t6.prp_id,
       t6.cliefat_endereco_o_mesmo,
       t6.cliefat_logradouro,
       t6.cliefat_numero,
       t6.cliefat_complemento,
       t6.cliefat_bairro,
       t6.cliefat_cep,
       t6.cliefat_cid_id_fk,
       t6.cliefat_obs_duplicata,
       t6.cliefat_email,
       t6.cliefat_cadastrado_por,
       t6.cliefat_cadastrado_em,
       t6.cliefat_alterado_por,
       t6.cliefat_alterado_em,
       t6.cliefat_versao,
       concat_ws(' - ',t7.cid_uf,t7.cid_municipio) AS cliefat_cid_nome,
       t8.prp_praca_pagto,
       t9.user_nome AS cliefat_cadastrado_por_nome,
       t10.user_nome AS cliefat_alterado_por_nome
FROM clientes t1
LEFT JOIN usuarios t2 on t2.user_id = t1.clie_cadastrado_por
LEFT JOIN usuarios t3 on t3.user_id = t1.clie_alterado_por
LEFT JOIN cidades t4 on t4.cid_id = t1.cid_id
LEFT JOIN rotas_entregas t5 on t5.rota_id = t1.rota_id
LEFT JOIN clientes_fatura t6 on t6.clie_id_fk = t1.clie_id
LEFT JOIN cidades t7 on t7.cid_id = t6.cliefat_cid_id_fk
LEFT JOIN praca_pagamento t8 on t8.prp_id = t6.prp_id
LEFT JOIN usuarios t9 on t9.user_id = t6.cliefat_cadastrado_por
LEFT JOIN usuarios t10 on t10.user_id = t6.cliefat_alterado_por
