-- Ultima atualizacao em 2021-11-22 as 18:38 - Adicionado coluna edi_caixa_postal
CREATE OR REPLACE VIEW view_empresas AS
SELECT t1.emp_id,
       t1.emp_razao_social,
       t1.emp_nome_fantasia,
       t1.emp_sigla_cia,
       t1.emp_cnpj,
       t1.emp_inscricao_estadual,
       t1.emp_logradouro,
       t1.emp_numero,
       t1.emp_complemento,
       t1.emp_bairro,
       t1.emp_cep,
       t1.cid_id_fk,
       t1.emp_fone1,
       t1.emp_fone2,
       t1.emp_tipo_emitente,
       t1.emp_modal,
       t1.emp_simples_nacional,
       t1.emp_PIS,
       t1.emp_COFINS,
       t1.emp_RNTRC,
       t1.emp_ativa,
       t1.emp_cte_modelo,
       t1.emp_cte_serie,
       t1.emp_versao_layout_xml,
       t1.emp_dacte_layout,
       t1.emp_seguradora,
       t1.emp_apolice,
       t1.emp_taxa_min_nac,
       t1.emp_email_contabil,
       t1.emp_email_comercial,
       t1.emp_email_CCO,
       t1.emp_enviar_cte,
       t1.emp_logotipo,
       t1.emp_aba_prod_perig,
       t1.emp_aba_doc_trans_ant,
       t1.emp_aba_veic_novos,
       t1.emp_aba_vale_pedagio,
       t1.emp_aba_veiculos,
       t1.emp_aba_motoristas,
       t1.emp_enabled_local_coleta,
       t1.emp_enabled_expedidor,
       t1.emp_enabled_recebedor,
       t1.emp_enabled_local_entrega,
       t1.emp_faturamento,
       t1.emp_dias_vecto,
       t1.emp_ambiente_sefaz,
       t1.emp_webservice_codigo,
       t1.emp_webservice_chave,
       t1.emp_smtp_servidor,
       t1.emp_smtp_pass,
       t1.emp_smtp_email,
       t1.emp_smtp_login,
       t1.emp_smtp_senha,
       t1.emp_smtp_porta,
       t1.emp_smtp_autentica,
       t1.emp_ftp_host,
       t1.emp_ftp_user,
       t1.emp_ftp_password,
       t1.emp_ftp_protocol,
       t1.emp_tipo_calculo_cubagem,
       t1.emp_portal,
       t1.emp_margem_lucro_min,
       t1.emp_margem_lucro_padrao,
       t1.emp_gmail1_login,
       t1.emp_gmail1_senha,
       t1.emp_gmail2_login,
       t1.emp_gmail2_senha,
       t1.emp_cadastrado_por,
       t1.emp_cadastrado_em,
       t1.emp_alterado_por,
       t1.emp_alterado_em,
       t1.emp_versao,
       t1.utc,
       t1.remote_file_path,
       t1.edi_caixa_postal,
       (case t1.emp_modal when 'Aereo' then '02' when 'Rodoviario' then '01' else '06' end) AS emp_modal_codigo,
       concat_ws(' - ',t1.emp_sigla_cia,t1.emp_nome_fantasia) AS emp_login,
       concat_ws('\n',concat_ws(' ',t1.emp_logradouro,t1.emp_numero,'-',t1.emp_complemento),concat_ws(' ',t1.emp_bairro,t1.emp_cep),concat_ws(' - ',t2.cid_uf,t2.cid_municipio)) AS emp_endereco,
       concat_ws(' - ',t2.cid_uf,t2.cid_municipio) AS cid_nome,
       left(t2.cid_codigo_municipio,2) AS cid_codigo_uf,
       t2.cid_codigo_municipio,
       t2.cid_municipio,
       t2.cid_uf,
       t2.cid_sigla,
       t2.cid_nome_aeroporto,
       t2.cid_suframa,
       t2.cid_valor_sefaz,
       t3.user_nome AS emp_cadastrado_por_nome,
       t4.user_nome AS emp_alterado_por_nome
FROM empresas t1
LEFT JOIN cidades t2 on t2.cid_id = t1.cid_id_fk
LEFT JOIN usuarios t3 on t3.user_id = t1.emp_cadastrado_por
LEFT JOIN usuarios t4 on t4.user_id = t1.emp_alterado_por